project/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

from accounts.views import home
from services.views import about_us_view
from services.views import contact_us_view

urlpatterns = [
    path('database/', admin.site.urls),
    path('', home, name='home'),
    path('about', about_us_view, name='about'),
    path('contact', contact_us_view, name='contact'),
    path('auth/', include('accounts.urls')),
    path('services/', include('services.urls')),
    path('admin/', include('services.urls_admin')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/services/urls.py
from django.urls import path

from .views import birthday_page_view
from .views import book_birthday_view
from .views import book_business_meeting_view
from .views import book_live_show_view
from .views import book_product_launch_view
from .views import book_wedding_view
from .views import business_meeting_page_view
from .views import candidate_register_view
from .views import college_tour_page_view
from .views import college_tour_view
from .views import company_details_view
from .views import company_view
from .views import construction_page_view
from .views import construction_service_page_view
from .views import construction_service_view
from .views import event_management_page_view
from .views import family_tour_page_view
from .views import family_tour_view
from .views import honeymoon_tour_page_view
from .views import honeymoon_view
from .views import human_resource_page_view
from .views import interior_2d_page_view
from .views import interior_3d_page_view
from .views import live_show_page_view
from .views import marketing_view
from .views import product_launch_page_view
from .views import solo_tour_page_view
from .views import solo_tour_view
from .views import tour_page_view
from .views import vacancy_submit_view
from .views import wedding_page_view

urlpatterns = [

    path('event/', event_management_page_view, name='event-management'),
    path('event/product-launch/', product_launch_page_view, name='event-management-product-launch'),
    path('event/business-meeting/', business_meeting_page_view, name='event-management-business-meeting'),
    path('event/live-show/', live_show_page_view, name='event-management-live-show'),
    path('event/wedding/', wedding_page_view, name='event-management-wedding'),
    path('event/birthday/', birthday_page_view, name='event-management-birthday'),
    path('event/product-launch/book/', book_product_launch_view, name='product-launch-booking'),
    path('event/business-meeting/book/', book_business_meeting_view, name='business-meeting-booking'),
    path('event/live-show/book/', book_live_show_view, name='live-show-booking'),
    path('event/wedding/book/', book_wedding_view, name='wedding-booking'),
    path('event/birthday/book/', book_birthday_view, name='birthday-booking'),

    path('construction/', construction_page_view, name='construction'),
    path('construction/construction/', construction_service_page_view, name='construction-construction'),
    path('construction/interior-2d-drawing/', interior_2d_page_view, name='construction-interior-2d-drawing'),
    path('construction/interior-3d-drawing/', interior_3d_page_view, name='construction-interior-3d-drawing'),
    path('construction/<str:service>/book/', construction_service_view, name='construction-service-booking'),

    path('tour/', tour_page_view, name='tour'),
    path('tour/solo-tour/', solo_tour_page_view, name='tour-solo-page'),
    path('tour/family-tour/', family_tour_page_view, name='tour-family-page'),
    path('tour/college-tour/', college_tour_page_view, name='tour-college-page'),
    path('tour/honeymoon/', honeymoon_tour_page_view, name='tour-honeymoon-page'),

    path('tour/solo-tour/book/', solo_tour_view, name='solo-tour-booking'),
    path('tour/family-tour/book/', family_tour_view, name='family-tour-booking'),
    path('tour/college-tour/book/', college_tour_view, name='college-tour-booking'),
    path('tour/honeymoon/book/', honeymoon_view, name='honeymoon-booking'),

    path('marketing/', marketing_view, name='marketing'),

    path('consultancy/human-resource/', human_resource_page_view, name='human-resource'),
    path('consultancy/register-candidate/', candidate_register_view, name='register-candidate'),
    path('consultancy/submit-vacancy/', vacancy_submit_view, name='submit-vacancy'),

    path('company/', company_view, name='company-page'),
    path('company/<int:company_id>/details', company_details_view, name='company-detail-page'),
]

project/services/models.py
from django.core.validators import MaxValueValidator
from django.core.validators import MinValueValidator
from django.db import models

from accounts.models import User

STATUS = (
    ('approved', 'Approved'),
    ('rejected', 'Rejected'),
    ('pending', 'Pending'),
)


class Company(models.Model):
    name = models.CharField(max_length=255)
    place = models.CharField(max_length=64)
    pin_code = models.IntegerField()
    phone_number = models.CharField(max_length=10)
    email = models.EmailField()
    company_type = models.CharField(max_length=128)
    bio = models.TextField()

    def __str__(self):
        return self.name


class Candidate(models.Model):
    CANDIDATE_TYPE = (
        ('student', 'Student'),
        ('working', 'Working'),
    )
    added_by = models.ForeignKey(to=User, on_delete=models.CASCADE)
    category = models.CharField(max_length=10, choices=CANDIDATE_TYPE)
    full_name = models.CharField(max_length=255)
    age = models.PositiveIntegerField(validators=[MaxValueValidator(99), MinValueValidator(18)])
    qualification = models.CharField(max_length=255)
    skills = models.TextField()
    job_position = models.CharField(max_length=256)
    address = models.CharField(max_length=256)
    pin_code = models.IntegerField()
    email = models.EmailField()
    resume = models.FileField(upload_to='candidate/resume/')

    def __str__(self):
        return f'Candidate {self.full_name}'


class Vacancy(models.Model):
    posted_by = models.ForeignKey(to=User, on_delete=models.CASCADE)
    company = models.ForeignKey(to=Company, on_delete=models.CASCADE, blank=True, null=True)
    post_name = models.CharField(max_length=256)
    number_of_post = models.IntegerField()
    skills = models.TextField()
    salary_package = models.CharField(max_length=256)
    job_description = models.CharField(max_length=512)
    experience = models.CharField(max_length=256)
    date_of_interview = models.DateField()
    venue = models.CharField(max_length=256)
    time = models.TimeField()

    def __str__(self):
        return self.post_name


class Event(models.Model):
    FOOD_TYPE = (
        ('veg', 'Vegetarian'),
        ('non-veg', 'Non-Vegetarian'),
    )
    TYPE_OF_VENUE = (
        ('ac', 'AC'),
        ('non-ac', 'Non-AC'),
    )
    TYPE_OF_EVENT = (
        ('product_launch', 'Product Launch'),
        ('business_meeting', 'Business Meeting'),
        ('live_show', 'Live Show'),
        ('wedding', 'Wedding'),
        ('birthday', 'Birthday')
    )
    booked_by = models.ForeignKey(to=User, on_delete=models.CASCADE)
    event_type = models.CharField(choices=TYPE_OF_EVENT, max_length=24)
    date_of_event = models.DateField()
    type_of_venue = models.CharField(choices=TYPE_OF_VENUE, max_length=12)
    number_of_person = models.IntegerField()
    food_items = models.CharField(choices=FOOD_TYPE, max_length=12)
    light_and_sound = models.TextField()
    number_of_days = models.IntegerField(blank=True, null=True)
    number_of_security = models.IntegerField(blank=True, null=True)
    amount = models.IntegerField(blank=True, null=True)
    transportation = models.IntegerField(blank=True, null=True)
    photography = models.IntegerField(blank=True, null=True)
    beautician = models.IntegerField(blank=True, null=True)
    status = models.CharField(choices=STATUS, default='pending', max_length=16)

    def __str__(self):
        return f'{self.get_event_type_display()}  booked by {str(self.booked_by)}'


class Construction(models.Model):
    SERVICE_TYPE = (
        ('construction', 'Construction'),
        ('interior_2d', 'Interior 2D Drawing'),
        ('interior_3d', 'Interior 3D Drawing'),
    )
    booked_by = models.ForeignKey(to=User, on_delete=models.CASCADE)
    service_type = models.CharField(choices=SERVICE_TYPE, max_length=16)
    number_of_day = models.IntegerField()
    square_feet = models.CharField(max_length=128)
    work_progress = models.CharField(max_length=64)
    construction_plan = models.ImageField(upload_to='construction-plan')
    status = models.CharField(choices=STATUS, default='pending', max_length=16)

    def __str__(self):
        return f'{self.get_service_type_display()} booked by {str(self.booked_by)}'


class Tour(models.Model):
    TOUR_TYPE = (
        ('solo', 'Solo Tour'),
        ('family', 'Family Tour'),
        ('college', 'College Tour'),
        ('honeymoon', 'Honeymoon'),
    )
    TYPE_OF_HOTEL = (
        ('ac', 'AC'),
        ('non-ac', 'Non-AC'),
    )
    FOOD_TYPE = (
        ('veg', 'Vegetarian'),
        ('non-veg', 'Non-Vegetarian'),
    )
    YES_OR_NO = (
        ('y', 'Yes'),
        ('n', 'No'),
    )
    booked_by = models.ForeignKey(to=User, on_delete=models.CASCADE)
    tour_type = models.CharField(choices=TOUR_TYPE, max_length=16)
    date = models.DateField()
    number_of_days = models.IntegerField()
    type_of_hotel = models.CharField(choices=TYPE_OF_HOTEL, max_length=12)
    food_items = models.CharField(choices=FOOD_TYPE, max_length=12)
    number_of_person = models.IntegerField()
    number_of_room = models.IntegerField(default=1)
    transportation = models.IntegerField(blank=True, null=True)
    number_of_boys = models.IntegerField(blank=True, null=True)
    number_of_girls = models.IntegerField(blank=True, null=True)
    number_of_staff = models.IntegerField(blank=True, null=True)
    need_tour_guid = models.CharField(choices=YES_OR_NO, max_length=1)
    status = models.CharField(choices=STATUS, default='pending', max_length=16)

    def __str__(self):
        return f'{self.get_tour_type_display()} booked by {str(self.booked_by)}'

project/services/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UsernameField

from accounts.models import ADMIN_TYPE
from accounts.models import User
from services.models import Candidate
from services.models import Company
from services.models import Construction
from services.models import Event
from services.models import Tour
from services.models import Vacancy


class ProductLaunchBookingForm(forms.ModelForm):
    date_of_event = forms.DateTimeField(input_formats=['%d/%m/%Y'])

    class Meta:
        model = Event
        fields = {
            'date_of_event',
            'type_of_venue',
            'number_of_person',
            'food_items',
            'light_and_sound',
        }


class BusinessMeetingBookingForm(forms.ModelForm):
    date_of_event = forms.DateTimeField(input_formats=['%d/%m/%Y'])

    class Meta:
        model = Event
        fields = {
            'date_of_event',
            'type_of_venue',
            'number_of_person',
            'food_items',
            'light_and_sound',
        }


class LiveShowBookingForm(forms.ModelForm):
    date_of_event = forms.DateTimeField(input_formats=['%d/%m/%Y'])

    class Meta:
        model = Event
        fields = {
            'date_of_event',
            'type_of_venue',
            'number_of_person',
            'number_of_security',
            'food_items',
            'light_and_sound',
        }


class WeddingBookingForm(forms.ModelForm):
    date_of_event = forms.DateTimeField(input_formats=['%d/%m/%Y'])

    class Meta:
        model = Event
        fields = {
            'date_of_event',
            'type_of_venue',
            'number_of_person',
            'number_of_security',
            'number_of_days',
            'amount',
            'transportation',
            'photography',
            'beautician',
            'food_items',
            'light_and_sound',
        }


class BirthdayBookingForm(forms.ModelForm):
    date_of_event = forms.DateTimeField(input_formats=['%d/%m/%Y'])

    class Meta:
        model = Event
        fields = {
            'date_of_event',
            'type_of_venue',
            'number_of_person',
            'amount',
            'food_items',
            'light_and_sound',
        }


class ConstructionForm(forms.ModelForm):
    work_progress = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Construction
        fields = {
            'number_of_day',
            'square_feet',
            'work_progress',
            'construction_plan',
        }


class SoloTourForm(forms.ModelForm):
    date = forms.DateTimeField(input_formats=['%d/%m/%Y'])

    class Meta:
        model = Tour
        fields = {
            'date',
            'number_of_days',
            'type_of_hotel',
            'food_items',
        }


class FamilyTourForm(forms.ModelForm):
    date = forms.DateTimeField(input_formats=['%d/%m/%Y'])

    class Meta:
        model = Tour
        fields = {
            'date',
            'number_of_days',
            'type_of_hotel',
            'food_items',
            'number_of_person',
            'transportation',
            'need_tour_guid',
        }


class CollegeTourForm(forms.ModelForm):
    date = forms.DateTimeField(input_formats=['%d/%m/%Y'])

    class Meta:
        model = Tour
        fields = {
            'date',
            'number_of_days',
            'number_of_boys',
            'number_of_girls',
            'number_of_staff',
            'number_of_room',
            'type_of_hotel',
            'food_items',
            'transportation',
            'need_tour_guid',
        }


class HoneymoonForm(forms.ModelForm):
    date = forms.DateTimeField(input_formats=['%d/%m/%Y'])

    class Meta:
        model = Tour
        fields = {
            'date',
            'number_of_days',
            'food_items',
            'type_of_hotel',
            'need_tour_guid',
        }


class CandidateForm(forms.ModelForm):
    class Meta:
        model = Candidate
        fields = {
            'category',
            'full_name',
            'age',
            'qualification',
            'skills',
            'job_position',
            'address',
            'pin_code',
            'email',
        }


class VacancyForm(forms.ModelForm):
    date_of_interview = forms.DateTimeField(input_formats=['%d/%m/%Y'])
    time = forms.DateTimeField(input_formats=['%H:%M'])

    class Meta:
        model = Vacancy
        fields = {
            'post_name',
            'number_of_post',
            'skills',
            'salary_package',
            'job_description',
            'experience',
            'date_of_interview',
            'venue',
            'time',
        }


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = '__all__'


class AdminLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data["username"]
        password = self.cleaned_data["password"]

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("Invalid credentials")
            if not user.check_password(password):
                raise forms.ValidationError("Invalid credentials")
            if not user.is_active:
                raise forms.ValidationError("This user is not longer active")

        return super(AdminLoginForm, self).clean()


class AdminCreateForm(forms.Form):
    username = UsernameField()
    first_name = forms.CharField(max_length=255)
    last_name = forms.CharField(max_length=255)
    password = forms.CharField(widget=forms.PasswordInput)
    admin_type = forms.ChoiceField(choices=ADMIN_TYPE)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data["username"]

        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("username already exist")
        return super(AdminCreateForm, self).clean()

project/templates/services/forms/birthday_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block contents %}
    <div class="hero-area2  slider-height2 hero-overly2 d-flex align-items-center" style="min-height: 250px">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap text-center pt-20">
                        <h2>{{ title }}</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="card p-lg-5 m-lg-5">
            <form method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-12 mb-0">
                        {{ form.date_of_event|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-3 mb-0">
                        {{ form.type_of_venue|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-3 mb-0">
                        {{ form.food_items|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-3 mb-0">
                        {{ form.number_of_person|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-3 mb-0">
                        {{ form.amount|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-12 mb-0">
                        {{ form.light_and_sound|as_crispy_field }}
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
    {% block extra-js %}
        <script>
            $(function () {
                $("#id_date_of_event").datepicker({
                    format: 'dd/mm/yyyy',
                });
            });
        </script>
    {% endblock %}
{% endblock %}

project/templates/services/forms/business_meeting_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block contents %}
    <div class="hero-area2  slider-height2 hero-overly2 d-flex align-items-center" style="min-height: 250px">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap text-center pt-20">
                        <h2>{{ title }}</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="card p-lg-5 m-lg-5">
            <form method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-12 mb-0">
                        {{ form.date_of_event|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-4 mb-0">
                        {{ form.type_of_venue|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-4 mb-0">
                        {{ form.food_items|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-4 mb-0">
                        {{ form.number_of_person|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-12 mb-0">
                        {{ form.light_and_sound|as_crispy_field }}
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
    {% block extra-js %}
        <script>
            $(function () {
                $("#id_date_of_event").datepicker({
                    format: 'dd/mm/yyyy',
                });
            });
        </script>
    {% endblock %}
{% endblock %}

project/templates/services/forms/college_tour_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block contents %}
    <div class="hero-area2  slider-height2 hero-overly2 d-flex align-items-center" style="min-height: 250px">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap text-center pt-20">
                        <h2>{{ title }}</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="card p-lg-5 m-lg-5">
            <form method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.date|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-2 mb-0">
                        {{ form.need_tour_guid|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-2 mb-0">
                        {{ form.type_of_hotel|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-2 mb-0">
                        {{ form.food_items|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">

                    <div class="form-group col-md-4 mb-0">
                        {{ form.number_of_days|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-4 mb-0">
                        {{ form.number_of_boys|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-4 mb-0">
                        {{ form.number_of_girls|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-4 mb-0">
                        {{ form.number_of_staff|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-4 mb-0">
                        {{ form.number_of_room|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-4 mb-0">
                        {{ form.transportation|as_crispy_field }}
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
    {% block extra-js %}
        <script>
            $(function () {
                $("#id_date").datepicker({
                    format: 'dd/mm/yyyy',
                });
            });
        </script>
    {% endblock %}
{% endblock %}

project/templates/services/forms/construction_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block contents %}
    <div class="hero-area2  slider-height2 hero-overly2 d-flex align-items-center" style="min-height: 250px">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap text-center pt-20">
                        <h2>{{ title }}</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="card p-lg-5 m-lg-5">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.number_of_day|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.square_feet|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-12 mb-0">
                        {{ form.work_progress|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-12 mb-0">
                        {{ form.construction_plan|as_crispy_field }}
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
    {% block extra-js %}
        <script>
            $(function () {
                $("#id_date_of_event").datepicker({
                    format: 'dd/mm/yyyy',
                });
            });
        </script>
    {% endblock %}
{% endblock %}

project/templates/services/forms/family_tour_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block contents %}
    <div class="hero-area2  slider-height2 hero-overly2 d-flex align-items-center" style="min-height: 250px">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap text-center pt-20">
                        <h2>{{ title }}</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="card p-lg-5 m-lg-5">
            <form method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.date|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-2 mb-0">
                        {{ form.number_of_days|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-2 mb-0">
                        {{ form.type_of_hotel|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-2 mb-0">
                        {{ form.food_items|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-4 mb-0">
                        {{ form.need_tour_guid|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-4 mb-0">
                        {{ form.number_of_person|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-4 mb-0">
                        {{ form.transportation|as_crispy_field }}
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
    {% block extra-js %}
        <script>
            $(function () {
                $("#id_date").datepicker({
                    format: 'dd/mm/yyyy',
                });
            });
        </script>
    {% endblock %}
{% endblock %}

project/templates/services/forms/honeymoon_tour_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block contents %}
    <div class="hero-area2  slider-height2 hero-overly2 d-flex align-items-center" style="min-height: 250px">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap text-center pt-20">
                        <h2>{{ title }}</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="card p-lg-5 m-lg-5">
            <form method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-4 mb-0">
                        {{ form.date|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-2 mb-0">
                        {{ form.number_of_days|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-2 mb-0">
                        {{ form.food_items|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-2 mb-0">
                        {{ form.type_of_hotel|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-2 mb-0">
                        {{ form.need_tour_guid|as_crispy_field }}
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
    {% block extra-js %}
        <script>
            $(function () {
                $("#id_date").datepicker({
                    format: 'dd/mm/yyyy',
                });
            });
        </script>
    {% endblock %}
{% endblock %}

project/templates/services/forms/live_show_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block contents %}
    <div class="hero-area2  slider-height2 hero-overly2 d-flex align-items-center" style="min-height: 250px">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap text-center pt-20">
                        <h2>{{ title }}</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="card p-lg-5 m-lg-5">
            <form method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-12 mb-0">
                        {{ form.date_of_event|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-3 mb-0">
                        {{ form.type_of_venue|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-3 mb-0">
                        {{ form.food_items|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-3 mb-0">
                        {{ form.number_of_person|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-3 mb-0">
                        {{ form.number_of_security|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-12 mb-0">
                        {{ form.light_and_sound|as_crispy_field }}
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
    {% block extra-js %}
        <script>
            $(function () {
                $("#id_date_of_event").datepicker({
                    format: 'dd/mm/yyyy',
                });
            });
        </script>
    {% endblock %}
{% endblock %}